events {}

http {
    server {
        listen 80;
        location /static/ {
            alias /app/productionfiles/;
        }
        location /media/ {
            alias /app/media/;
        }
        location / {
            proxy_pass http://web:8000;
        }
    }
}